### ISSUE TITLE
Intellij settings image is gone

### ISSUE THREAD

**Issue by gricey432** [gavanitrate/zeroc-ice-gradle-boilerplate#1]
The example image referenced in README.md is no longer available. Could it be uploaded to a different host?

**Comment by gavanitrate** [comment]
![image](https://user-images.githubusercontent.com/8264198/37464581-7909d9c4-28a4-11e8-8b00-d0ca4a203070.png)
i was just referring to this panel in IntelliJ. unfortunately, I don't have ICE installed anymore, so I can't show a working example. Feel free to upload this image anywhere you see fit.
